top_srcdir   = /tmp/httpd-2.4.9
top_builddir = /tmp/httpd-2.4.9
srcdir       = /tmp/httpd-2.4.9/modules/gami
builddir     = /tmp/httpd-2.4.9/modules/gami
VPATH        = /tmp/httpd-2.4.9/modules/gami
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
